---
sudo: required
language: python
cache: pip
services:
  - docker
install:
  - pip install molecule docker
script:
  - molecule lint
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
